[package]
name = "aoc-2015-day15"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
helpers = {path = "../../helpers"}
bitflags = "2.4.1"
itertools = "0.11.0"
thiserror = "1.0.50"
